// <auto-generated />
using System;
using LeltarKezelo.Szerver.Adat;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeltarKezelo.Szerver.Adat.Migraciok
{
    [DbContext(typeof(LeltarDbContext))]
    partial class LeltarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FelhasznaloLeltarkorzet", b =>
                {
                    b.Property<long>("FelhasznaloId")
                        .HasColumnType("bigint");

                    b.Property<long>("JogosultKorzetekId")
                        .HasColumnType("bigint");

                    b.HasKey("FelhasznaloId", "JogosultKorzetekId");

                    b.HasIndex("JogosultKorzetekId");

                    b.ToTable("FelhasznaloLeltarkorzet");
                });

            modelBuilder.Entity("FelhasznaloSzerepkor", b =>
                {
                    b.Property<long>("FelhasznalokId")
                        .HasColumnType("bigint");

                    b.Property<long>("SzerepkorokId")
                        .HasColumnType("bigint");

                    b.HasKey("FelhasznalokId", "SzerepkorokId");

                    b.HasIndex("SzerepkorokId");

                    b.ToTable("FelhasznaloSzerepkor");
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.AllapotValtozas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EszkozId")
                        .HasColumnType("bigint");

                    b.Property<long>("FelhasznaloId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Idopont")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Indoklas")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("RegiAllapotId")
                        .HasColumnType("bigint");

                    b.Property<string>("Ugyiratszam")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("UjAllapotId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FelhasznaloId");

                    b.HasIndex("RegiAllapotId");

                    b.HasIndex("UjAllapotId");

                    b.HasIndex("EszkozId", "Idopont");

                    b.ToTable("AllapotValtozas", (string)null);
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.AuditNaplo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Entitas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("EntitasId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FelhasznaloId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Idopont")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Muvelet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RegiErtekJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UjErtekJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FelhasznaloId");

                    b.HasIndex("Idopont");

                    b.HasIndex("Entitas", "EntitasId");

                    b.ToTable("AuditNaplo", (string)null);
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.Elhelyezes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ErvenyesIg")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("ErvenyesTol")
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("EszkozId")
                        .HasColumnType("bigint");

                    b.Property<string>("Forras")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("HelyisegId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LeolvasasId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EszkozId")
                        .IsUnique()
                        .HasDatabaseName("IX_Elhelyezes_EszkozId_Aktualis")
                        .HasFilter("[ErvenyesIg] IS NULL");

                    b.HasIndex("HelyisegId");

                    b.HasIndex("LeolvasasId");

                    b.HasIndex("EszkozId", "ErvenyesTol");

                    b.ToTable("Elhelyezes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Elhelyezes_Ervenyesseg", "[ErvenyesIg] IS NULL OR [ErvenyesIg] > [ErvenyesTol]");

                            t.HasCheckConstraint("CK_Elhelyezes_Forras", "[Forras] IN ('LELTAR', 'KEZI')");
                        });
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.ElvartTetel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ElvartMennyiseg")
                        .HasColumnType("int");

                    b.Property<long>("EszkozId")
                        .HasColumnType("bigint");

                    b.Property<string>("FelvitelOka")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("LeltarIdoszakId")
                        .HasColumnType("bigint");

                    b.Property<long>("LeltarkorzetId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EszkozId");

                    b.HasIndex("LeltarkorzetId");

                    b.HasIndex("LeltarIdoszakId", "EszkozId")
                        .IsUnique();

                    b.ToTable("ElvartTetel", null, t =>
                        {
                            t.HasCheckConstraint("CK_ElvartTetel_ElvartMennyiseg", "[ElvartMennyiseg] > 0");

                            t.HasCheckConstraint("CK_ElvartTetel_FelvitelOka", "[FelvitelOka] IN ('PILLANATKEP', 'UTOLAGOS')");
                        });
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.Eszkoz", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("BeszerzesDatuma")
                        .HasColumnType("date");

                    b.Property<int>("ElvartMennyiseg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("Ertek")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("EszkozAllapotId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EszkozTipusId")
                        .HasColumnType("bigint");

                    b.Property<long>("LeltarkorzetId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LetrehoztaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Megjegyzes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Megnevezes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MennyisegiEgyseg")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("ModositottaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Modositva")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("EszkozAllapotId");

                    b.HasIndex("EszkozTipusId");

                    b.HasIndex("LeltarkorzetId");

                    b.HasIndex("Megnevezes");

                    b.ToTable("Eszkoz", null, t =>
                        {
                            t.HasCheckConstraint("CK_Eszkoz_ElvartMennyiseg", "[ElvartMennyiseg] > 0");
                        });
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.EszkozAllapot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Megszunt")
                        .HasColumnType("bit");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Sorrend")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nev")
                        .IsUnique();

                    b.ToTable("EszkozAllapot", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Megszunt = false,
                            Nev = "aktív",
                            Sorrend = 1
                        },
                        new
                        {
                            Id = 2L,
                            Megszunt = false,
                            Nev = "javítás alatt",
                            Sorrend = 2
                        },
                        new
                        {
                            Id = 3L,
                            Megszunt = false,
                            Nev = "kölcsönadva",
                            Sorrend = 3
                        },
                        new
                        {
                            Id = 4L,
                            Megszunt = false,
                            Nev = "selejtezésre javasolt",
                            Sorrend = 4
                        },
                        new
                        {
                            Id = 5L,
                            Megszunt = true,
                            Nev = "selejtezett",
                            Sorrend = 5
                        },
                        new
                        {
                            Id = 6L,
                            Megszunt = true,
                            Nev = "elveszett",
                            Sorrend = 6
                        },
                        new
                        {
                            Id = 7L,
                            Megszunt = true,
                            Nev = "ellopott",
                            Sorrend = 7
                        },
                        new
                        {
                            Id = 8L,
                            Megszunt = true,
                            Nev = "átadva",
                            Sorrend = 8
                        });
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.EszkozKod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Aktiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Ertek")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ErtekNorm")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComputedColumnSql("UPPER(LTRIM(RTRIM([Ertek])))", true);

                    b.Property<long>("EszkozId")
                        .HasColumnType("bigint");

                    b.Property<long>("KodTipusId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ErtekNorm")
                        .IsUnique()
                        .HasFilter("[Aktiv] = 1");

                    b.HasIndex("EszkozId");

                    b.HasIndex("KodTipusId");

                    b.ToTable("EszkozKod", (string)null);
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.EszkozTipus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("SzuloId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SzuloId");

                    b.ToTable("EszkozTipus", (string)null);
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.FelelosHozzarendeles", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ErvenyesIg")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("ErvenyesTol")
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("EszkozId")
                        .HasColumnType("bigint");

                    b.Property<long>("FelelosId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EszkozId")
                        .IsUnique()
                        .HasDatabaseName("IX_FelelosHozzarendeles_EszkozId_Aktualis")
                        .HasFilter("[ErvenyesIg] IS NULL");

                    b.HasIndex("FelelosId");

                    b.HasIndex("EszkozId", "ErvenyesTol");

                    b.ToTable("FelelosHozzarendeles", null, t =>
                        {
                            t.HasCheckConstraint("CK_FelelosHozzarendeles_Ervenyesseg", "[ErvenyesIg] IS NULL OR [ErvenyesIg] > [ErvenyesTol]");
                        });
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.FelelosSzemely", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Aktiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Azonosito")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("FelhasznaloId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SzervezetiEgyseg")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Azonosito")
                        .IsUnique()
                        .HasFilter("[Azonosito] IS NOT NULL");

                    b.HasIndex("FelhasznaloId")
                        .IsUnique()
                        .HasFilter("[FelhasznaloId] IS NOT NULL");

                    b.HasIndex("Nev");

                    b.ToTable("FelelosSzemely", (string)null);
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.Felhasznalo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Felhasznalonev")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JelszoHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SzervezetiEgyseg")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UtolsoBelepes")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("Felhasznalonev")
                        .IsUnique();

                    b.ToTable("Felhasznalo", (string)null);
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.Helyiseg", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Aktiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Emelet")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Epulet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Megnevezes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Szobaszam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Vonalkod")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Vonalkod")
                        .IsUnique()
                        .HasFilter("[Vonalkod] IS NOT NULL");

                    b.HasIndex("Epulet", "Szobaszam")
                        .IsUnique();

                    b.ToTable("Helyiseg", (string)null);
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.ImportFutas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Fajlnev")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long>("FelhasznaloId")
                        .HasColumnType("bigint");

                    b.Property<int>("Hibas")
                        .HasColumnType("int");

                    b.Property<DateTime>("Idopont")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("Sikeres")
                        .HasColumnType("int");

                    b.Property<int>("SorokSzama")
                        .HasColumnType("int");

                    b.Property<string>("Statusz")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("FelhasznaloId");

                    b.HasIndex("Idopont");

                    b.ToTable("ImportFutas", null, t =>
                        {
                            t.HasCheckConstraint("CK_ImportFutas_Statusz", "[Statusz] IN ('FOLYAMATBAN', 'SIKERES', 'RESZLEGES', 'SIKERTELEN')");
                        });
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.ImportHiba", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ertek")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("ImportFutasId")
                        .HasColumnType("bigint");

                    b.Property<string>("Oszlop")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Sor")
                        .HasColumnType("int");

                    b.Property<string>("Uzenet")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ImportFutasId");

                    b.ToTable("ImportHiba", (string)null);
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.Kiegeszito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ErvenyesIg")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("ErvenyesTol")
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("FoEszkozId")
                        .HasColumnType("bigint");

                    b.Property<long?>("KiegeszitoEszkozId")
                        .HasColumnType("bigint");

                    b.Property<string>("Leiras")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Mennyiseg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("FoEszkozId");

                    b.HasIndex("KiegeszitoEszkozId");

                    b.ToTable("Kiegeszito", null, t =>
                        {
                            t.HasCheckConstraint("CK_Kiegeszito_Ervenyesseg", "[ErvenyesIg] IS NULL OR [ErvenyesIg] > [ErvenyesTol]");

                            t.HasCheckConstraint("CK_Kiegeszito_Mennyiseg", "[Mennyiseg] > 0");

                            t.HasCheckConstraint("CK_Kiegeszito_NemOnmaga", "[KiegeszitoEszkozId] IS NULL OR [KiegeszitoEszkozId] <> [FoEszkozId]");

                            t.HasCheckConstraint("CK_Kiegeszito_Tartalom", "[KiegeszitoEszkozId] IS NOT NULL OR [Leiras] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.KiegeszitoEllenorzes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("KiegeszitoId")
                        .HasColumnType("bigint");

                    b.Property<long>("LeolvasasId")
                        .HasColumnType("bigint");

                    b.Property<string>("Mod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("KiegeszitoId");

                    b.HasIndex("LeolvasasId", "KiegeszitoId")
                        .IsUnique();

                    b.ToTable("KiegeszitoEllenorzes", null, t =>
                        {
                            t.HasCheckConstraint("CK_KiegeszitoEllenorzes_Mod", "[Mod] IN ('KOZVETLEN', 'FELTETELEZETT')");
                        });
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.KodTipus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("VonalkodkentHasznalhato")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Nev")
                        .IsUnique();

                    b.ToTable("KodTipus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Aktiv = true,
                            Nev = "SAP szám",
                            VonalkodkentHasznalhato = true
                        },
                        new
                        {
                            Id = 2L,
                            Aktiv = true,
                            Nev = "Leltári szám 1",
                            VonalkodkentHasznalhato = true
                        },
                        new
                        {
                            Id = 3L,
                            Aktiv = true,
                            Nev = "Leltári szám 2",
                            VonalkodkentHasznalhato = true
                        },
                        new
                        {
                            Id = 4L,
                            Aktiv = true,
                            Nev = "Gyártási szám",
                            VonalkodkentHasznalhato = true
                        },
                        new
                        {
                            Id = 5L,
                            Aktiv = true,
                            Nev = "Belső vonalkód",
                            VonalkodkentHasznalhato = true
                        });
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.LeltarIdoszak", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("Kezdete")
                        .HasColumnType("date");

                    b.Property<long?>("LezartaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Lezarva")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Megnevezes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Statusz")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tipus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly?>("Vege")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("LezartaId");

                    b.ToTable("LeltarIdoszak", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeltarIdoszak_Idoszak", "[Vege] IS NULL OR [Vege] >= [Kezdete]");

                            t.HasCheckConstraint("CK_LeltarIdoszak_Lezaras", "[Statusz] <> 'LEZART' OR [Lezarva] IS NOT NULL");

                            t.HasCheckConstraint("CK_LeltarIdoszak_Statusz", "[Statusz] IN ('TERVEZETT', 'NYITOTT', 'LEZART')");

                            t.HasCheckConstraint("CK_LeltarIdoszak_Tipus", "[Tipus] IN ('EVES', 'RENDKIVULI')");
                        });
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.Leltarkorzet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SzervezetiEgyseg")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Leltarkorzet", (string)null);
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.Leolvasas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AktivKorzetId")
                        .HasColumnType("bigint");

                    b.Property<string>("BeolvasottKod")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("BeviteliMod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<long?>("EszkozId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EszkozKodId")
                        .HasColumnType("bigint");

                    b.Property<long>("FelhasznaloId")
                        .HasColumnType("bigint");

                    b.Property<long?>("HelyisegId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Idopont")
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("LeltarIdoszakId")
                        .HasColumnType("bigint");

                    b.Property<int>("Mennyiseg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Minosites")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("SztornoIdopont")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("SztornoIndoklas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("SztornoztaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Sztornozva")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AktivKorzetId");

                    b.HasIndex("BeolvasottKod");

                    b.HasIndex("EszkozId");

                    b.HasIndex("EszkozKodId");

                    b.HasIndex("FelhasznaloId");

                    b.HasIndex("HelyisegId");

                    b.HasIndex("SztornoztaId");

                    b.HasIndex("LeltarIdoszakId", "EszkozId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("LeltarIdoszakId", "EszkozId"), new[] { "Mennyiseg", "Minosites", "Sztornozva" });

                    b.HasIndex("LeltarIdoszakId", "Idopont");

                    b.ToTable("Leolvasas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Leolvasas_BeviteliMod", "[BeviteliMod] IN ('OLVASO', 'KAMERA', 'BEILLESZTES', 'KEZI', 'DEMO')");

                            t.HasCheckConstraint("CK_Leolvasas_Eszkoz", "([Minosites] = 'ISMERETLEN_KOD' AND [EszkozId] IS NULL) OR ([Minosites] <> 'ISMERETLEN_KOD' AND [EszkozId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Leolvasas_Mennyiseg", "[Mennyiseg] > 0");

                            t.HasCheckConstraint("CK_Leolvasas_Minosites", "[Minosites] IN ('OK', 'MAS_KORZET', 'ISMETELT', 'TOBBLET', 'ISMERETLEN_KOD', 'NEM_AKTIV')");

                            t.HasCheckConstraint("CK_Leolvasas_Sztorno", "[Sztornozva] = 0 OR ([SztornoIndoklas] IS NOT NULL AND [SztornoIdopont] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.Szerepkor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nev")
                        .IsUnique();

                    b.ToTable("Szerepkor", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Nev = "Admin"
                        },
                        new
                        {
                            Id = 2L,
                            Nev = "Leltarfelelos"
                        },
                        new
                        {
                            Id = 3L,
                            Nev = "Leltarozo"
                        },
                        new
                        {
                            Id = 4L,
                            Nev = "Megtekinto"
                        });
                });

            modelBuilder.Entity("FelhasznaloLeltarkorzet", b =>
                {
                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Felhasznalo", null)
                        .WithMany()
                        .HasForeignKey("FelhasznaloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Leltarkorzet", null)
                        .WithMany()
                        .HasForeignKey("JogosultKorzetekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FelhasznaloSzerepkor", b =>
                {
                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Felhasznalo", null)
                        .WithMany()
                        .HasForeignKey("FelhasznalokId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Szerepkor", null)
                        .WithMany()
                        .HasForeignKey("SzerepkorokId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.AllapotValtozas", b =>
                {
                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Eszkoz", "Eszkoz")
                        .WithMany()
                        .HasForeignKey("EszkozId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Felhasznalo", "Felhasznalo")
                        .WithMany()
                        .HasForeignKey("FelhasznaloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.EszkozAllapot", "RegiAllapot")
                        .WithMany()
                        .HasForeignKey("RegiAllapotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.EszkozAllapot", "UjAllapot")
                        .WithMany()
                        .HasForeignKey("UjAllapotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eszkoz");

                    b.Navigation("Felhasznalo");

                    b.Navigation("RegiAllapot");

                    b.Navigation("UjAllapot");
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.AuditNaplo", b =>
                {
                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Felhasznalo", "Felhasznalo")
                        .WithMany()
                        .HasForeignKey("FelhasznaloId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Felhasznalo");
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.Elhelyezes", b =>
                {
                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Eszkoz", "Eszkoz")
                        .WithMany()
                        .HasForeignKey("EszkozId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Helyiseg", "Helyiseg")
                        .WithMany()
                        .HasForeignKey("HelyisegId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Leolvasas", "Leolvasas")
                        .WithMany()
                        .HasForeignKey("LeolvasasId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Eszkoz");

                    b.Navigation("Helyiseg");

                    b.Navigation("Leolvasas");
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.ElvartTetel", b =>
                {
                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Eszkoz", "Eszkoz")
                        .WithMany()
                        .HasForeignKey("EszkozId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.LeltarIdoszak", "LeltarIdoszak")
                        .WithMany("ElvartTetelek")
                        .HasForeignKey("LeltarIdoszakId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Leltarkorzet", "Leltarkorzet")
                        .WithMany()
                        .HasForeignKey("LeltarkorzetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eszkoz");

                    b.Navigation("LeltarIdoszak");

                    b.Navigation("Leltarkorzet");
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.Eszkoz", b =>
                {
                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.EszkozAllapot", "EszkozAllapot")
                        .WithMany()
                        .HasForeignKey("EszkozAllapotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.EszkozTipus", "EszkozTipus")
                        .WithMany()
                        .HasForeignKey("EszkozTipusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Leltarkorzet", "Leltarkorzet")
                        .WithMany()
                        .HasForeignKey("LeltarkorzetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EszkozAllapot");

                    b.Navigation("EszkozTipus");

                    b.Navigation("Leltarkorzet");
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.EszkozKod", b =>
                {
                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Eszkoz", "Eszkoz")
                        .WithMany("Kodok")
                        .HasForeignKey("EszkozId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.KodTipus", "KodTipus")
                        .WithMany()
                        .HasForeignKey("KodTipusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eszkoz");

                    b.Navigation("KodTipus");
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.EszkozTipus", b =>
                {
                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.EszkozTipus", "Szulo")
                        .WithMany()
                        .HasForeignKey("SzuloId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Szulo");
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.FelelosHozzarendeles", b =>
                {
                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Eszkoz", "Eszkoz")
                        .WithMany()
                        .HasForeignKey("EszkozId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.FelelosSzemely", "Felelos")
                        .WithMany()
                        .HasForeignKey("FelelosId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eszkoz");

                    b.Navigation("Felelos");
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.FelelosSzemely", b =>
                {
                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Felhasznalo", "Felhasznalo")
                        .WithMany()
                        .HasForeignKey("FelhasznaloId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Felhasznalo");
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.ImportFutas", b =>
                {
                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Felhasznalo", "Felhasznalo")
                        .WithMany()
                        .HasForeignKey("FelhasznaloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Felhasznalo");
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.ImportHiba", b =>
                {
                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.ImportFutas", "ImportFutas")
                        .WithMany("Hibak")
                        .HasForeignKey("ImportFutasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportFutas");
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.Kiegeszito", b =>
                {
                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Eszkoz", "FoEszkoz")
                        .WithMany()
                        .HasForeignKey("FoEszkozId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Eszkoz", "KiegeszitoEszkoz")
                        .WithMany()
                        .HasForeignKey("KiegeszitoEszkozId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FoEszkoz");

                    b.Navigation("KiegeszitoEszkoz");
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.KiegeszitoEllenorzes", b =>
                {
                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Kiegeszito", "Kiegeszito")
                        .WithMany()
                        .HasForeignKey("KiegeszitoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Leolvasas", "Leolvasas")
                        .WithMany()
                        .HasForeignKey("LeolvasasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kiegeszito");

                    b.Navigation("Leolvasas");
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.LeltarIdoszak", b =>
                {
                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Felhasznalo", "Lezarta")
                        .WithMany()
                        .HasForeignKey("LezartaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lezarta");
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.Leolvasas", b =>
                {
                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Leltarkorzet", "AktivKorzet")
                        .WithMany()
                        .HasForeignKey("AktivKorzetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Eszkoz", "Eszkoz")
                        .WithMany()
                        .HasForeignKey("EszkozId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.EszkozKod", "EszkozKod")
                        .WithMany()
                        .HasForeignKey("EszkozKodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Felhasznalo", "Felhasznalo")
                        .WithMany()
                        .HasForeignKey("FelhasznaloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Helyiseg", "Helyiseg")
                        .WithMany()
                        .HasForeignKey("HelyisegId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.LeltarIdoszak", "LeltarIdoszak")
                        .WithMany()
                        .HasForeignKey("LeltarIdoszakId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeltarKezelo.Szerver.Adat.Entitasok.Felhasznalo", "Sztornozta")
                        .WithMany()
                        .HasForeignKey("SztornoztaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AktivKorzet");

                    b.Navigation("Eszkoz");

                    b.Navigation("EszkozKod");

                    b.Navigation("Felhasznalo");

                    b.Navigation("Helyiseg");

                    b.Navigation("LeltarIdoszak");

                    b.Navigation("Sztornozta");
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.Eszkoz", b =>
                {
                    b.Navigation("Kodok");
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.ImportFutas", b =>
                {
                    b.Navigation("Hibak");
                });

            modelBuilder.Entity("LeltarKezelo.Szerver.Adat.Entitasok.LeltarIdoszak", b =>
                {
                    b.Navigation("ElvartTetelek");
                });
#pragma warning restore 612, 618
        }
    }
}
